/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cave_on_an_alien_planet_skybox.glb 
Author: Jungle Jim (https://sketchfab.com/jungle_jim)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cave-on-an-alien-planet-skybox-25aebeb12d8b481190bef3e86c3c2ddf
Title: Cave on an alien planet (Skybox)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Cave_on_an_alien_planet_skybox(props) {
  const { nodes, materials } = useGLTF('/models/cave_on_an_alien_planet_skybox.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Sphere_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} scale={4091.932} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/cave_on_an_alien_planet_skybox.glb')
