/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 djinnis_curse_-_stylized_prop.glb 
Author: EnesTali (https://sketchfab.com/EnesTali)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/djinnis-curse-stylized-prop-a739dbe4f90940e887e9c5aa97ad2b42
Title: Djinni's Curse - Stylized Prop
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Djinnis_curse_stylized_prop(props) {
  const { nodes, materials } = useGLTF('/models/djinnis_curse_-_stylized_prop.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.17}>
        <mesh geometry={nodes.InstrumentBow_low_M_Djinnolin_C_0.geometry} material={materials.M_Djinnolin_C} position={[-6.715, 0, -2.323]} rotation={[0, -0.077, 0]} />
        <mesh geometry={nodes.Arm_L_low_M_Djinnolin_C_0.geometry} material={materials.M_Djinnolin_C} position={[-6.866, 0, -1.768]} rotation={[0, -0.077, 0]} />
        <mesh geometry={nodes.Arm_R_low_M_Djinnolin_C_0.geometry} material={materials.M_Djinnolin_C} position={[31.595, 40.811, 16.408]} rotation={[0.088, -0.415, 0.738]} scale={0.9} />
        <mesh geometry={nodes.Instrument_low_M_Djinnolin_C_0.geometry} material={materials.M_Djinnolin_C} position={[0, 57.327, 1.343]} />
        <mesh geometry={nodes.SM_ArmFX_M_Fx_C_0.geometry} material={materials.M_Fx_C} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/djinnis_curse_-_stylized_prop.glb')
