/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 escultura2.glb 
Author: MWintersberger (https://sketchfab.com/mwintersberger)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gottwaig-wunderkammer21-3d-ai-skybox-3e54ce7644e84439a94face66b7a4080
Title: GöttwAIg – Wunderkammer(21) | 3D AI Skybox
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Escultura2(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/escultura2.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              {/* <group name="Object_0" rotation={[Math.PI / 2, 0, 0]} scale={2}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
              </group> */}
              <group name="tripo_node_7516b2e1-b672-42c7-8b2c-02f2aec57579_1" position={[0, 0.65, 0]} scale={3}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['tripo_material_7516b2e1-b672-42c7-8b2c-02f2aec57579']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/escultura2.glb')
