/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 nebula_skybox_16k.glb 
Author: Jungle Jim (https://sketchfab.com/jungle_jim)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nebula-skybox-16k-0d1e380993a842e6a0111f09c5cb6bdc
Title: Nebula skybox 16k
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Nebula(props) {
  const { nodes, materials } = useGLTF('/models/nebula_skybox_16k.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Nebula_Skybox_Material001_0.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/nebula_skybox_16k.glb')
