/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robot_girl_with_hair_wires.glb 
Author: GR-video (https://sketchfab.com/grvideotv)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-girl-with-hair-wires-ccaa2e655374415c84bc1bb1b177681a
Title: Robot girl with hair wires
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Robot_girl_with_hair_wires(props) {
  const { nodes, materials } = useGLTF('/models/robot_girl_with_hair_wires.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.001, 0]} scale={[1.03, 1, 1]}>
        <mesh geometry={nodes.Object_13.geometry} material={materials.skin} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.skin} />
      </group>
      <group position={[-0.011, 2.012, 0.424]} rotation={[0.011, 0, 0]} scale={9.6}>
        <mesh geometry={nodes.Object_20.geometry} material={materials['.HG_Eyes_Outer_FAST']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['.HG_Eyes_Inner']} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Lines} position={[0, -0.001, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.metall} position={[0, -0.001, 0]} scale={[1.03, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/models/robot_girl_with_hair_wires.glb')
