/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 woman.glb 
Author: GR-video (https://sketchfab.com/grvideotv)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/woman-1342409c17124410a7657c758ee41138
Title: Woman
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Women(props) {
  const { nodes, materials } = useGLTF('/models/woman.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['tripo_mat_235af7df-60c1-4d09-9fa0-697642fd223d']} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['tripo_mat_235af7df-60c1-4d09-9fa0-697642fd223d']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['tripo_mat_235af7df-60c1-4d09-9fa0-697642fd223d']} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['tripo_mat_235af7df-60c1-4d09-9fa0-697642fd223d']} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['tripo_mat_235af7df-60c1-4d09-9fa0-697642fd223d']} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['tripo_mat_235af7df-60c1-4d09-9fa0-697642fd223d']} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['tripo_mat_235af7df-60c1-4d09-9fa0-697642fd223d']} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['tripo_mat_235af7df-60c1-4d09-9fa0-697642fd223d']} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['tripo_mat_235af7df-60c1-4d09-9fa0-697642fd223d']} />
      <mesh geometry={nodes.Object_13.geometry} material={materials['tripo_mat_235af7df-60c1-4d09-9fa0-697642fd223d']} />
    </group>
  )
}

useGLTF.preload('/models/woman.glb')
